server:
  port: 8002

spring:
  application:
    name: microservice-consumer-movie-ribbon-customizing-properties


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
#  instance:
#    perfer-ip-address: true

logging:
#  pattern:
#    console: "%d - %msg%n"
  level:
    root: debug

microservice-provider-user-ribbon:
  ribbon:
    NFLoadBalanceerRuleClassName: com.netflix.loadbalancer.RnadomRule
