server:
  port: 8001
spring:
  application:
    name: microservice-provider-user-trace-zikpin
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    platform: h2
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql
    url: jdbc:h2:mem:dbtest
    username: root
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2
      enabled: true
  zipkin:
    base-url: http://localhost:8000  #指定 Zikpin 地址
  sleuth:
    percentage: 1.0  #指定采样的请求的百分比
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG
