spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sc1?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: admin@mysql

  application:
    name: microservice-provider-user-ribbon

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
#  instance:
#    perfer-ip-address: true

server:
  port: 8001

logging:
  level:
    root: debug
