server:
  port: 8000
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Tonyzhangl/spring-cloud-demo
          search-paths: chapter7/config
          default-label: master

#      label: master
