server:
  port: 8002

spring:
  application:
    name: microservice-consumer-movie-hystrix-fallback-stream


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
#  instance:
#    perfer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
