spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    platform: h2
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql
    url: jdbc:h2:mem:dbtest
    username: root
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2
      enabled: true

  application:
    name: microservice-provider-user

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    perfer-ip-address: true


server:
  port: 8002
