server:
  port: 8002

spring:
  application:
    name: microservice-consumer-movie-ribbon


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
#  instance:
#    perfer-ip-address: true

logging:
#  pattern:
#    console: "%d - %msg%n"
  level:
    root: debug
