spring:
  application:
    name: microservice-consumer-movie-fegin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    perfer-ip-address: true


server:
  port: 8001

feign:
  hystrix:
    enabled: true
